### ISSUE TITLE
Реализация нескольких блоков на одной странице

### ISSUE THREAD

**Issue by ildarmustafin** [renat2985/rgb#12]
Здравствуйте. Как создать блоки в два столбика? Пробовал делать по ID блока (#url-content, #edit-content). но происходит наложение при нажатии на Ctrl+M. Я думаю у вас реализовано по другому﻿

**Comment by renat2985** [comment]
Какая у вас версия, за какое число?

**Comment by ildarmustafin** [comment]
У меня не ваша система. Я делаю свой проект, взяв за основу вашу. У меня все работает, но хотелось бы сделать более рациональным страницы. Точнее сделать из двух страниц два блока и разместить их на одну страницу.

**Comment by ildarmustafin** [comment]
Вроде понял. Нужно смотреть index.gz, index2.gz, index3.gz. Осталось разобраться с функциями внутри
